version: '3.8'

services:
  mariadb:
    build:
      context: .
    image: ghcr.io/concepting-com-br/mariadb:${BUILD_VERSION}
    container_name: mariadb
    hostname: mariadb
    ports: 
      - 3306:3306
    volumes:
      - mariadb-data:/home/user/data  
      - mariadb-log:/home/user/log  
    depends_on:
      - etcd
      
  etcd:
    image: ghcr.io/concepting-com-br/etcd:1.0.0
    container_name: etcd
    hostname: etcd
    ports: 
      - 2379:2379
    volumes:
      - ./etc/settings.json:/home/user/etc/mariadb.json
      - etcd-data:/home/user/data

volumes:
  mariadb-data:
  mariadb-log:
  etcd-data:
  