name: Docker

on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      BUILD_VERSION: 1.0.0
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: ./build.sh
      - name: Publish the Docker image
        run: ./publish.sh
        